spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot
    username: root
    password: 980529
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        hbm2dd1:
          auto: update
    show-sql: true